<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(NetStandardTargetFrameworks)</TargetFramework>
		<EnablePackageValidation>true</EnablePackageValidation>
		<PackageValidationBaselineVersion>2.0.0</PackageValidationBaselineVersion>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="..\Codeworx.Rest.Client\Internal\CodeworxRestClientInternalServiceCollectionExtensions.cs" Link="Internal\CodeworxRestClientInternalServiceCollectionExtensions.cs" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Codeworx.Rest.Primitives\Codeworx.Rest.Primitives.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Internal\" />
	</ItemGroup>
</Project>
