<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(NetStandardTargetFrameworks)</TargetFramework>
		<TreatWarningsAsErrors>false</TreatWarningsAsErrors>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Remove="StyleCop.Analyzers" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="System.Runtime.Serialization.Primitives" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Codeworx.Rest.Primitives\Codeworx.Rest.Primitives.csproj" />
	</ItemGroup>
</Project>