<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFrameworks>$(DotNetTargetFrameworks)</TargetFrameworks>
		<LangVersion>Latest</LangVersion>
		<PackAsTool>true</PackAsTool>
		<ToolCommandName>dotnet-restcontract</ToolCommandName>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CommandLineParser" />
		<PackageReference Include="Microsoft.Build.Framework" ExcludeAssets="runtime" />
		<PackageReference Include="Microsoft.Build.Locator" />
		<PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" />
		<PackageReference Include="System.Text.Json" />
		<PackageReference Include="System.Security.Cryptography.Pkcs" />
		<PackageReference Include="System.Security.Cryptography.Xml" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Codeworx.Rest.Formatters.Newtonsoft\Codeworx.Rest.Formatters.Newtonsoft.csproj" />
		<ProjectReference Include="..\Codeworx.Rest.Primitives\Codeworx.Rest.Primitives.csproj" />
	</ItemGroup>
</Project>